# Generated by Django 5.0.3 on 2024-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='hora',
            field=models.TimeField(),
        ),
    ]
