# Generated by Django 5.0.3 on 2024-03-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefa_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
