# Generated by Django 5.0.3 on 2024-03-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_data_atualizacao_usuario_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_atualizacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
